# Generated by Django 5.1.6 on 2025-02-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_frame', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(blank=True, max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('trivia_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('bus', 'bus'), ('cycling', 'cycling'), ('recycle', 'recycle')], default='bus', max_length=10)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Gamekeeper',
            fields=[
                ('gamekeeper_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamekeepers', to='myapp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0)),
                ('deck', models.CharField(blank=True, max_length=200)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campus')),
            ],
        ),
    ]
