# Generated by Django 5.1.6 on 2025-02-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoint',
            old_name='check_id',
            new_name='checkpoint_id',
        ),
        migrations.RenameField(
            model_name='gamekeeper',
            old_name='location',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deck',
        ),
        migrations.AddField(
            model_name='player',
            name='deck',
            field=models.ManyToManyField(blank=True, to='myapp.card'),
        ),
        migrations.CreateModel(
            name='GamekeeperTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gamekeeper')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
            options={
                'unique_together': {('gamekeeper', 'task')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
            options={
                'unique_together': {('player', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
            options={
                'unique_together': {('player', 'card')},
            },
        ),
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.checkpoint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
            options={
                'unique_together': {('task', 'checkpoint')},
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_time', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.checkpoint')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
            options={
                'unique_together': {('player', 'checkpoint', 'visited_time')},
            },
        ),
    ]
