# Generated by Django 5.1.6 on 2025-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_player_name_remove_player_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
    ]
