# Generated by Django 5.1.6 on 2025-02-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
