# Generated by Django 5.1.6 on 2025-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
            preserve_default=False,
        ),
    ]
