# Generated by Django 5.1.6 on 2025-03-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('location', 'location'), ('group', 'group')], default='daily', max_length=50),
        ),
    ]
