# Generated by Django 5.1.6 on 2025-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('location', 'location'), ('group', 'group'), ('bus', 'bus'), ('cycle', 'cycle'), ('walk', 'walk'), ('recycling', 'recycling'), ('water', 'water'), ('electric', 'electric'), ('streatham', 'streatham'), ('st lukes', 'st lukes'), ('skibidi', 'skibidi')], max_length=50, unique=True),
        ),
    ]
