# Generated by Django 5.1.6 on 2025-03-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('location', 'location'), ('group', 'group'), ('bus', 'bus'), ('cycle', 'cycle'), ('walk', 'walk'), ('recycling', 'recycling'), ('water', 'water'), ('electric', 'electric'), ('streatham', 'streatham'), ('st lukes', 'st lukes')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='kind',
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
    ]
