# Generated by Django 5.1.6 on 2025-03-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
