# Generated by Django 5.1.6 on 2025-03-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_kind'),
        ('myapp', '0004_playerachievement'),
    ]

    operations = [
    ]
