# Generated by Django 5.1.7 on 2025-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_0002_alter_task_kind_0004_playerachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
