# Generated by Django 5.1.6 on 2025-03-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_playerachievement_count_playerachievement_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertask',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playerachievement',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
