# Generated by Django 5.1.6 on 2025-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_playertask_progress_alter_achievement_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='logo',
            field=models.CharField(default='default.png', max_length=1000),
        ),
    ]
