# Generated by Django 5.1.6 on 2025-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_card_picture_alter_achievement_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('common', 'common'), ('uncommon', 'uncommon'), ('rare', 'rare'), ('legendary', 'legendary')], default='common', max_length=10),
        ),
    ]
